### ISSUE TITLE
Update Bitwarden

### ISSUE THREAD

**Issue by idominiki** [fbartels/univention-bitwarden#3]
Hi Felix,

how can I update Bitwarden on UCS? Does it work as mentioned here:
https://github.com/dani-garcia/bitwarden_rs/wiki/Updating-the-bitwarden-image

Thanks and Greets
Dominik

**Comment by fbartels** [comment]
Your question is answered in the readme at https://github.com/fbartels/univention-bitwarden#updating

**Comment by idominiki** [comment]
Oh sorry!
Does this also apply if I have Bitwarden installed from the UCS AppCenter?

**Comment by fbartels** [comment]
No, the app in the Univention Appcenter is not related to this repository. Instead of bitwarden_rs it's also using the official implementation afaik.

Only Univention can publish updates to apps in it's appcenter.
